services:
  postgres:
    image: postgres:latest
    container_name: sortify-postgres
    restart: always
    environment:
      POSTGRES_DB: sortify-backend-db
      POSTGRES_USER: sortify-admin
      POSTGRES_PASSWORD: sortify-password
    ports:
      - "5432:5432"
    networks:
      - sortify-network

  backend:
    build:
      context: ./backend
    container_name: sortify-backend
    restart: always
    ports:
      - "9876:9876"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://sortify-postgres:5432/sortify-backend-db
      SPRING_DATASOURCE_USERNAME: sortify-admin
      SPRING_DATASOURCE_PASSWORD: sortify-password
    depends_on:
      - postgres
    networks:
      - sortify-network

  frontend:
    build:
      context: ./frontend/sortify
    container_name: sortify-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - sortify-network

networks:
  sortify-network:
    driver: bridge
