import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Footer from "@/components/footer/footer";
import Page from "./page";
import styles from "./layout.module.css"
import { SearchProvider } from "@/app/context/searchContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Sortify",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
            <div className={styles.pageWrapper}>
                <SearchProvider>
                    <Header/>
                    {children}
                </SearchProvider>
                <Footer/>
            </div>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}