import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/header/header"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Footer from "./component/footer/footer";
import MainContent from "../app/mainContent";
import styles from "./layout.module.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Sortify",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
            <div className={styles.pageWrapper}>
                <Header/>
                <main className={styles.mainWrapper}>
                    <MainContent/>
                </main>
                <Footer/>
            </div>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}